version: '3'
services:
  api:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    env_file:
      - .env
    environment:
      - PORT=8080
      - DB_NAME=splitfest
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASS=password
      - DB_PORT=3306
    command: npm run api:dev:docker
    ports:
      - 8080:8080 # API Entry port
      - 4311:4311 # Server Debugging port
  web:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run web:dev:docker
    env_file:
      - .env
    environment:
      - PORT=8081
      - API_URL=http://host.docker.internal:8080
    ports:
      - 8081:8081
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db-volume:/var/lib/mysql
# Names our volume
volumes:
  mono-node-modules: null
  db-volume:
