version: '3'
services:
  api:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    environment:
      - PORT=8080
    command: npm run api:dev:docker
    ports:
      - 8080:8080 # API Entry port
      - 4311:4311 # Server Debugging port
  web:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run web:dev:docker
    environment:
      - PORT=8081
      - API_URL=http://host.docker.internal:8080
    ports:
      - 8081:8081

volumes:
  mono-node-modules: null
